### ISSUE TITLE
Make the fault phantom type polykinded

### ISSUE THREAD

**Issue by ramirez7** [ramirez7/monad-fault#2]
Right now, it has to be a `Symbol`. We can make it polykinded and still use `Symbol`s fine.

This will allow the user to use some more restricted DataKind as their fault phantom.

**Comment by schell** [comment]
Fault Phantom - the new band debuts on Warp with their hit single "Be Polykinded".

**Comment by ramirez7** [comment]
https://github.com/ramirez7/monad-fault/commit/6879812da7f77fcfdff1deaab2ac03336d443e1c resolved this
